### ISSUE TITLE
install error: ixa_tok expects jar file in folder components

### ISSUE THREAD

**Issue by piekvossen** [cltl/vu-rm-pip3#2]
Failed running idx_tok because it is expect the JAR file in the folder "components" but in fact it is installed in "modules". Renaming the folder "modules" into "components" fixes the problem.

-- Running ixa_tok
Error: Unable to access jarfile /Tools/vu-rm-pip3/components/java/ixa-pipe-tok-1.8.5-exec.jar
module ixa_tok returned an error

**Comment by sarnoult** [comment]
Solved with commit c1792aa
