### ISSUE TITLE
Cannot run Alpino on Mac OS X

### ISSUE THREAD

**Issue by piekvossen** [cltl/vu-rm-pip3#4]
I get the following error after the tokenisation was done successfully, trying to run Alpino. I get the same error trying to run Alpino outside the pipeline from the command line: 

PiekMacPro:create_bin piek$ ./Alpino.bin
-bash: ./Alpino.bin: cannot execute binary file

The input NAF for the pipeline is the following:

<?xml version="1.0" encoding="UTF-8"?>
<NAF xml:lang="nl" version="v1.naf">
  <nafHeader>
    <linguisticProcessors layer="text">
      <lp name="ixa-pipe-tok-nl" beginTimestamp="2018-10-17T12:29:49+0200" endTimestamp="2018-10-17T12:29:50+0200" version="1.8.5-22046489b892163a5d42a388d09019c481f2ca58" hostname="PiekMacPro.local" />
    </linguisticProcessors>
    <linguisticProcessors layer="entities">
      <lp name="ixa-pipe-nerc-nl-6-class-clusters-sonar" beginTimestamp="2018-10-17T12:29:50+0200" endTimestamp="2018-10-17T12:29:56+0200" version="1.6.1-1cdc3c3924b49b3d86fc2243b40becb7818120fb" hostname="PiekMacPro.local" />
    </linguisticProcessors>
  </nafHeader>
  <text>
    <wf id="w1" offset="0" length="3" sent="1" para="1">Dit</wf>
    <wf id="w2" offset="4" length="2" sent="1" para="1">is</wf>
    <wf id="w3" offset="7" length="3" sent="1" para="1">een</wf>
    <wf id="w4" offset="11" length="5" sent="1" para="1">leuke</wf>
    <wf id="w5" offset="17" length="5" sent="1" para="1">tweet</wf>
    <wf id="w6" offset="23" length="3" sent="1" para="1">van</wf>
    <wf id="w7" offset="27" length="3" sent="1" para="1">mij</wf>
    <wf id="w8" offset="30" length="1" sent="1" para="1">.</wf>
  </text>
</NAF>

The error in the log is:

-- Running alpino
[2018-10-17 12:29:50,550 root         INFO ] Calling Alpino with 1 sentences
/Tools/vu-rm-pip3/components/resources/Alpino/bin/Alpino: line 15: ldd: command not found
/Tools/vu-rm-pip3/components/resources/Alpino/bin/Alpino: line 24: /Tools/vu-rm-pip3/components/resources/Alpino/create_bin/Alpino.bin: cannot execute binary file
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Tools/vu-rm-pip3/components/python/morphosyntactic_parser_nl/alpinonaf/__main__.py", line 25, in <module>
in_obj = parse(input_file, max_min_per_sent=args.max_minutes)
File "/Tools/vu-rm-pip3/components/python/morphosyntactic_parser_nl/alpinonaf/morph_syn_parser.py", line 330, in parse
for sentence, tree, dependencies in call_alpino(sentences, max_min_per_sent):
File "/Tools/vu-rm-pip3/components/python/morphosyntactic_parser_nl/alpinonaf/morph_syn_parser.py", line 254, in call_alpino_local
raise Exception("Call to alpino failed (see logs): %s" % cmd)
Exception: Call to alpino failed (see logs): /Tools/vu-rm-pip3/components/resources/Alpino/bin/Alpino user_max=12000 end_hook=xml -flag treebank /var/folders/ht/_fx2jf216xb_vrtykf56v7c40000gp/T/tmpxmvah8p9 -parse
module alpino returned an error

**Comment by sarnoult** [comment]
It looks like you are missing a library:
> ldd:command not found

Do you have Developer tools on your Mac?

**Comment by piekvossen** [comment]
I found out that "ldd" does not work on Mac os x. Instead you should use the command "oTool -L". SO I replaced "ldd" by "oTool -L" in the file:

components/resources/Alpino/bin/Alpino

which now says:

"if ( oTool -L $ALPINO_HOME/create_bin/Alpino.bin | grep -q -E '(libtcl|libtk).*not found' )
then
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ALPINO_HOME/create_bin/extralibs
    export TCL_LIBRARY=$ALPINO_HOME/create_bin/extralibs/tcl8.6
    export TK_LIBRARY=$ALPINO_HOME/create_bin/extralibs/tk8.6
fi"

It does not fix it, as I now get the error:

llvm-objdump: '/Tools/vu-rm-pip3/components/resources/Alpino/create_bin/Alpino.bin': Object is not a Mach-O file type.


 I think the "ldd" error is however just a warning and not fatal. What is fatal is the next command:

/Tools/vu-rm-pip3/components/resources/Alpino/bin/Alpino: line 24: /Tools/vu-rm-pip3/components/resources/Alpino/create_bin/Alpino.bin: cannot execute binary file

The problem must be that Alpino is not compiled for Unix. Depending on the OS, we need to compile Alpino differently I guess. This is what it says in the INSTALL file of Alpino:

====================================================================

  - to build Alpino on Mac OS X or Windows, set the 'PLATFORM'
    variable to 'darwin' or 'windows' respectively in Makefile.defs

  - building Alpino on Windows requires Visual Studio 2005


=====================================================================

**Comment by sarnoult** [comment]
Thanks, I will mention that in the Readme of the next commit.
