### ISSUE TITLE
run_pipeline.sh

### ISSUE THREAD

**Issue by piekvossen** [cltl/vu-rm-pip3#5]
Explain in the readme that the path needs to be adapted in the run_pipeline.sh
It now says:

wrapper_dir=/home/arnoult/vu-rm-pip3
# you can copy this config file and adapt it as you wish 
#cfg=$wrapper_dir/example/pipeline.yml

**Comment by sarnoult** [comment]
Thanks, I will change it to a relative path in the next commit.

**Comment by piekvossen** [comment]
ok.
