### ISSUE TITLE
Alpino 'setitimer' error on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by lbogaardt** [cltl/vu-rm-pip3#6]
When **Alpino** parses sentences, it can time how long each sentence takes and can stop parsing if a maximum time is passed (see the documentation of the '_user_max_' flag on the [guide](http://www.let.rug.nl/vannoord/alp/Alpino/AlpinoUserGuide.html)).

When the pipeline is installed on the **Windows Subsystem for Linux**, and the pipeline is tested (using '_cat example/test.txt | run-pipeline.sh > output.naf_'), the following error is logged in '_pipeline.log_':

> -- Running alpino
[2018-11-05 11:17:46,004 root         INFO ] Calling Alpino with 10 sentences
hdrug: process 4761 on host ESLT0081 (datime(2018,11,5,11,17,50))
! System error
! '$start_timer_a/3: \'setitimer\' failed: Invalid argument'

It seems timing the parsing of each sentence, using '_setitimer_', does not work.

One way to by-pass this error is to leave empty the '_user_max_' flag. In this pipeline, setting the '_user_max_' flag occurs via a **Python** script. In '_scripts/bin/alpino_', the '-t' flag is set. In '_components/python/morphosyntactic_parser_nl/alpinonaf/main.py_', this '-t' argument is passed on to the '_morph_syn_parser.py_' and subsequently sets the '_user_max_' flag. So by removing the '-t 0.2' in '_scripts/bin/alpino_', the '_setitimer_' error can be avoided.

Nonetheless, this issue should be solved properly, if that's possible under the **Windows Subsystem for Linux.**

**Comment by sarnoult** [comment]
I plan to let the run-pipeline.sh script take this argument directly. To be closed soon.

**Comment by sarnoult** [comment]
commit d6c84f7 allows to set the alpino user_max (max_minutes) -t flag when calling the pipeline. The flag is unset by default.

**Comment by lbogaardt** [comment]
I agree that this allows the user to easily by-pass the problem, by not setting the -t flag. However, the 'real' problem is with the 'setitimer' call, which is not solved. Anyway, it's a minor thing and should not have priority, but we should also not forget about it.
