### ISSUE TITLE
Python3 compatibility of Opinion Miner Deluxe

### ISSUE THREAD

**Issue by lbogaardt** [cltl/vu-rm-pip3#7]
From the ReadMe:

> Not all python components are python3-compatible yet. Call the script ./scripts/util/port-to-python3.sh to back-up the relevant modules and convert them to python2/3-compatible code. The script uses 2to3, futurize and module-specific patches.

One change between *Python2* and *Python3* is the way accelerated versions of modules are imported (see this [StackExchange](https://stackoverflow.com/questions/43550407/pip-install-pickle-not-working-no-such-file-or-directory)).

However, in the '_components\python\opinion_miner_deluxePP\extract_features_xx.py_' files, the following lines remain in *Python2* style:

> try:
   import cPickle as pickler
except ValueError:
   import pickle as pickler

This should be changed to:

> import _pickle as pickler

Preferably, this change should occur automatically within the '_./scripts/util/port-to-python3.sh_' script.

**Comment by lbogaardt** [comment]
It seems there was a problem with installing the module 2To3. This should be added to the '_env/requirements.txt_'. Once it is installed, the error above no longer occurs.

**Comment by sarnoult** [comment]
lib2to3 is now mentioned as a requirement, I have also updated './scripts/util/opin-to-python3.sh' to rewrite the python2-style lines appropriately.
